#!/usr/bin/env bash
# A/B comparison: baseline binary vs arena-optimized binary, B=8/16/32/64.
# Each binary uses keys generated by itself (key file layout differs by padding).
set -u
export LD_LIBRARY_PATH=/usr/local/cuda-12.8/lib64:${LD_LIBRARY_PATH:-}
G=/home/ecs-user/idash26/gpu-mpc-track/gpu_mpc
BASE=$G/deepdtagen_inference_baseline
OPT=$G/deepdtagen_inference

sample_dir() {
  case $1 in
    8)  echo $G/timing_b8 ;;
    16) echo $G/timing_b16 ;;
    32) echo $G/eval_b32 ;;
    64) echo $G/eval_b64 ;;
  esac
}
cap_for() { case $1 in 8) echo 4;; 16) echo 4;; 32) echo 8;; 64) echo 12;; esac; }

run_one() { # $1=binary $2=B $3=tag $4=extra_env
  local BIN=$1 B=$2 TAG=$3 ENVX=$4 S KD CAP
  S=$(sample_dir $B); KD=/dev/shm/cmp_k; CAP=$(cap_for $B)
  rm -rf $KD && mkdir -p $KD
  env DDG_KEYBUF_CAP_GB=$CAP DDG_WEIGHTS_BIN=$S/weights.bin $BIN 32 12 0 0 $KD/ $S $B >/dev/null 2>&1 || { echo "$TAG B=$B dealer0 FAILED"; return 1; }
  env DDG_KEYBUF_CAP_GB=$CAP DDG_WEIGHTS_BIN=$S/weights.bin $BIN 32 12 0 1 $KD/ $S $B >/dev/null 2>&1 || { echo "$TAG B=$B dealer1 FAILED"; return 1; }
  env $ENVX DDG_WEIGHTS_BIN=$S/weights.bin $BIN 32 12 1 1 $KD/ $S $B 127.0.0.1 > /tmp/cmp_${TAG}_1_$B.log 2>&1 &
  sleep 1
  env $ENVX DDG_WEIGHTS_BIN=$S/weights.bin $BIN 32 12 1 0 $KD/ $S $B 127.0.0.1 > /tmp/cmp_${TAG}_0_$B.log 2>&1
  wait
  rm -rf $KD
}

for B in 8 16 32 64; do
  echo "=== B=$B baseline ==="
  run_one $BASE $B base "DDG_KEY_ARENA=0"
  echo "=== B=$B optimized ==="
  run_one $OPT  $B opt  "DDG_KEY_ARENA_PCT=95"
done
echo "ALL DONE"
